name: CI

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          working-directory: gobarber-back
        

      # Install NPM/Yarn dependencies
      - name: Install dependencies
        run:  yarn
        working-directory: gobarber-back

      # Run the build
      - name: Run build
        run:  yarn build
        working-directory: gobarber-back
      
      - name: Copy dist folder to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          working-directory: gobarber-back
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"

    # Copy dist folder to Digital Ocean
    
    # Replace current code at dist folder for the new onw
    # Run "yarn" at Digital Ocean
    # Run TypeORM migrations
    # Restart Node.js at the server
    
